version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    ports:
      - 3000:3000
    environment:
      NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    working_dir: /app  
